title: Kian Zohoury
logo: /assets/img/logo.png
description: Hi ğŸ‘‹ğŸ¼, welcome to my personal blog. Here, I showcase my latest projects and talk about AI.
email: kzohoury@berkeley.edu
url: "https://kianzohoury.github.io"
github_username:  kianzohoury
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
